<a href="https://colab.research.google.com/github/zyn20/Linear-Regression-Model-ML/blob/main/PythonPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
name = input('What is your name')
print(name)

What is your namezain
zain


In [ ]:
candidates = ['zain','abdullah','Zahida','Fahad','Zahid','Faisal']
for cand in candidates:
  print(cand)

zain
abdullah
Zahida
Fahad
Zahid
Faisal


In [ ]:
largest = None
numbers = [10,20,211,-321,-1000]
for i in numbers:
  if largest is None or i > largest:
    largest = i
    print('Loop',i,largest)
print(largest)

Loop 10 10
Loop 20 20
Loop 211 211
211


In [ ]:
print(min('zain'))

a


In [ ]:
print(ord('a'))

97


In [ ]:
import random

In [ ]:
random.random()

0.5258391037658452

In [ ]:
random.randint(1,10)

7

In [ ]:
names = ['Zain','Zaeem','Abudllah']
random.choice(names)

'Zain'

In [ ]:
def randonFunction (names):
  return random.choice(names)


In [ ]:
randonFunction(['ZAin','ABD'])

'ABD'

In [ ]:
stringg = 'Mera naam zian hai'
print(stringg[5:])


naam zian hai


In [ ]:
name = 'zain'
new = 'P'+name[1:]
print(new)

Pain


In [ ]:
word = 'fuckmefuckemfuckemfud'
count = 0
for i in word:
  if i=='f':
    count=count+1
  else:
    pass
print('The cout of a is :', count)

The cout of a is : 4


In [ ]:
'a' in 'zain'

True

In [ ]:
dir(word)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [ ]:
word.upper()

'FUCKMEFUCKEMFUCKEMFUD'

In [ ]:
help(word.upper())

No Python documentation found for 'FUCKMEFUCKEMFUCKEMFUD'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [ ]:
word.find('m')

4

In [ ]:
line = 'My name is zain               '
line.strip()

'My name is zain'

In [ ]:
line.startswith('My')

True

In [ ]:
word = 'Pakistan'
dic = {}
for i in word:
  if i not in dic:
    dic[i] = 1
  else:
    dic[i] = dic[i] + 1
print(dic)

{'P': 1, 'a': 2, 'k': 1, 'i': 1, 's': 1, 't': 1, 'n': 1}


In [ ]:
RollNumbers = {'1':'Zain','2':'Abdullah','3':'Shahzain','4':'Rehman'}
print(RollNumbers.get('1','Null'))
print(RollNumbers.get('10','UDEMY'))


Zain
UDEMY


In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4,5])
print(x.shape)

(5,)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x[0] = 7
print(x)

[7 2 3 4 5]


In [ ]:
new = np.array([1,2,3,4])
x= new>2
print(x)
new[x]

[False False  True  True]


array([3, 4])

In [ ]:
new.shape

(1, 4)

In [ ]:
new = np.array([[1,4,5],[2,3,4],[7,8,6]])
new[:,2]

array([5, 4, 6])

In [ ]:
new.shape

(2, 3)

In [ ]:
matrix1= np.array([1,2,3,4,5])
matrix2= np.array([1,2,3,4,5])
sum = matrix1+matrix2

In [ ]:
sum.T


array([ 2,  4,  6,  8, 10])

Suppose we want to add some matric element to each row


In [ ]:
mat = np.array([[1,2,3],[3,5,3],[123,2,1],[5,4,2]])

In [ ]:
vect1 = np.array([1,0,1])


In [ ]:
new_vect =vect1+mat

In [ ]:
new_vect

array([[  2,   2,   4],
       [  4,   5,   4],
       [124,   2,   2],
       [  6,   4,   3]])

In [ ]:
new_array


array([[  2,   2,   4],
       [  4,   5,   4],
       [124,   2,   2],
       [  6,   4,   3]])

broadcasting in numpy